### ISSUE TITLE
Hey there is an error in the responsiveness of the website 

### ISSUE THREAD

**Issue by DhruvWebDev** [piyush-eon/tanstack-query-weather-app#1]
like this component 👇👇👇
![image](https://github.com/user-attachments/assets/84a6f9b4-1dfb-4e57-adfe-5877aafb2e9e)

**Comment by piyush-eon** [comment]
I think you shrinked it beyond the limit. works fine on my device.

**Comment by DhruvWebDev** [comment]
ok....
